"""
task5/ui_consistency_checker.py
===============================
Reads Task 4 UI extractions and runs a two-pass consistency and spell check algorithm.
Writes defects directly to the UI_DEFECTS database table and outputs a summary JSON.

Two-pass Strategy:
1. First pass globally identifies dominant button casings and CSS classes.
2. Second pass spell-checks static/mixed text (after stripping interpolations) and 
   flags deviations in buttons from the globally dominant standards.

Outputs:
  - task5/ui_consistency_report.json
  - MySQL ui_defects table
"""

import os
import json
import logging
import re
from pathlib import Path
from collections import defaultdict

# ── Logging Setup ─────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(levelname)-8s %(name)s -- %(message)s")
logger = logging.getLogger("task5_ui_checker")

import sys
# Ensure we can import from core db library
# If this script is at audit_tool/task5/ui_consistency_checker.py, BASE should be audit_tool
BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE / "task2_audit"))

import yaml
from db.db_writer import write_ui_defect, _get_connection

try:
    from spellchecker import SpellChecker
except ImportError:
    SpellChecker = None
    logger.warning("pyspellchecker is not installed. Spelling checks will be skipped.")


# ── Config and Constants ──────────────────────────────────────────────────────
CONFIG_PATH = BASE / "task2_audit" / "config" / "project_config.yaml"
TECH_WORDS_PATH = BASE / "task2_audit" / "config" / "web_tech_words.txt"
# We read the extraction file generated by Task 4
EXTRACTION_PATH = BASE / "task4" / "ui_extraction.json"
OUTPUT_REPORT_PATH = BASE / "task5" / "ui_consistency_report.json"

KNOWN_FORMATS = {
  "json", "csv", "xml", "yaml", "html", "css",
  "js", "vue", "png", "jpg", "svg", "pdf",
  "config", "env", "log", "txt", "md"
}

if not os.path.exists(BASE / "task5"):
    os.makedirs(BASE / "task5", exist_ok=True)

import html

def _clean_text(text: str) -> str:
    """Run exact 4-step cleaning BEFORE compound splitting."""
    if not text: return ""
    text = html.unescape(text)
    text = re.sub(r'<[^>]+>', ' ', text)
    text = re.sub(r'\{\{.*?\}\}', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def _split_words(text: str) -> list:
    """Split CamelCase, snake_case, kebab-case into tokens."""
    if not text: return []
    text = text.replace('_', ' ').replace('-', ' ')
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)
    text = re.sub(r'[^A-Za-z\s]', ' ', text)
    
    words = []
    for w in text.split():
        w = w.strip()
        if w: words.append(w)
    return words

# ── Main Class ───────────────────────────────────────────────────────────────
class UIConsistencyChecker:
    def __init__(self, cfg):
        self.cfg = cfg
        self.ignore_words = set(cfg.get("spelling", {}).get("ignore_words", []))
        self.global_button_casings = defaultdict(lambda: defaultdict(int))
        self.global_button_classes = defaultdict(lambda: defaultdict(int))
        self.dominant_casing = {}
        self.dominant_class = {}
        self.global_word_counts = defaultdict(int)
        
        self.spell = SpellChecker() if SpellChecker else None
        if self.spell:
            # Register project specific safe words
            self.spell.word_frequency.load_words([w.lower() for w in self.ignore_words])
            # Load web technical dictionary if available
            if TECH_WORDS_PATH.exists():
                with open(TECH_WORDS_PATH, "r", encoding="utf-8") as f:
                    tech_words = [line.strip().lower() for line in f if line.strip()]
                self.spell.word_frequency.load_words(tech_words)
            
        self.seen_words_cache = {} # str -> True (clean) / False (misspelled)
        self.file_map = self._build_file_map()

    def _build_file_map(self):
        conn = _get_connection(self.cfg)
        cur = conn.cursor()
        try:
            cur.execute("SELECT id, file_path FROM vue_files")
            return {row[1].replace('\\', '/').lower(): row[0] for row in cur.fetchall()}
        except Exception as e:
            logger.error("Failed to build file map: %s", e)
            return {}
        finally:
            cur.close()
            conn.close()

    def load_data(self):
        if not EXTRACTION_PATH.exists():
            logger.error("UI extraction file not found at %s. Please run Task 4 first.", EXTRACTION_PATH)
            return None
        with open(EXTRACTION_PATH, "r", encoding="utf-8") as f:
            return json.load(f).get("uiExtraction", [])

    def fetch_file_id(self, filepath: str) -> int:
        """Fetch the DB ID for the file using robust endswith matching."""
        clean_path = filepath.lower()
        for db_path, fid in self.file_map.items():
            if db_path.endswith(clean_path):
                return fid
        return 0

    def pass_one(self, data: list):
        """Pass 1: Accumulate global frequencies for buttons and build word corpus."""
        for file_rec in data:
            # 1. Buttons
            for btn in file_rec.get("buttons", []):
                text = btn.get("text", "").strip()
                if not text:
                    continue
                lower_str = text.lower()
                self.global_button_casings[lower_str][text] += 1
                cclass = btn.get("class", "").strip()
                if cclass:
                    self.global_button_classes[lower_str][cclass] += 1

                btn_type = btn.get("type", "static")
                if btn_type != "i18n":
                    clean_text = _clean_text(text)
                    if "lorem ipsum" not in clean_text.lower():
                        for w in _split_words(clean_text):
                            if w.isupper() or len(w) < 3 or w.isnumeric(): continue
                            self.global_word_counts[w.lower()] += 1

            # 2. Headers
            for header in file_rec.get("headers", []):
                text = header.get("text", "").strip()
                if text and header.get("type", "static") != "i18n":
                    clean_text = _clean_text(text)
                    if "lorem ipsum" not in clean_text.lower():
                        for w in _split_words(clean_text):
                            if w.isupper() or len(w) < 3 or w.isnumeric(): continue
                            self.global_word_counts[w.lower()] += 1
            
            # 3. Visible Texts
            for vtext in file_rec.get("visibleTexts", []):
                text = vtext.get("text", "").strip()
                if text and vtext.get("type", "static") != "i18n":
                    clean_text = _clean_text(text)
                    if "lorem ipsum" not in clean_text.lower():
                        for w in _split_words(clean_text):
                            if w.isupper() or len(w) < 3 or w.isnumeric(): continue
                            self.global_word_counts[w.lower()] += 1

        # Determine dominants
        for lower_str, counts in self.global_button_casings.items():
            self.dominant_casing[lower_str] = max(counts.items(), key=lambda x: x[1])[0]
        for lower_str, counts in self.global_button_classes.items():
            if counts:
                self.dominant_class[lower_str] = max(counts.items(), key=lambda x: x[1])[0]
                
        # Load corpus into spellchecker
        if self.spell:
            domain_words = [w for w, c in self.global_word_counts.items() if c >= 2]
            self.spell.word_frequency.load_words(domain_words)

    def check_spelling_and_lorem(self, text: str) -> list:
        """Returns defects using 8-filter pipeline and Lorem Ipsum detection."""
        if not text: return []
        defects = []
        clean_text = _clean_text(text)
        
        if "lorem ipsum" in clean_text.lower():
            return [{"type": "PLACEHOLDER_TEXT_IN_PRODUCTION", "severity": "MEDIUM", "trigger": clean_text, "expected": "Remove placeholder"}]
            
        if not self.spell: return []
        
        words = _split_words(clean_text)
        for w in words:
            if w.isupper(): continue
            if len(w) < 3: continue
            
            lw = w.lower()
            if lw in KNOWN_FORMATS: continue
            if w.isnumeric(): continue
            
            if lw in self.seen_words_cache:
                is_valid = self.seen_words_cache[lw]
            else:
                is_valid = (lw not in self.spell.unknown([lw]))
                self.seen_words_cache[lw] = is_valid
                
            if is_valid: continue
            
            if self.global_word_counts[lw] >= 2: continue
            
            expected = self.spell.correction(lw) or lw
            defects.append({
                "type": "SPELLING",
                "severity": "LOW",
                "trigger": w,
                "expected": expected
            })
            
        return defects

    def pass_two_evaluate_files(self, data: list) -> list:
        """Pass 2: Score files, run spell check, generate defects."""
        report_data = []
        
        for file_rec in data:
            filepath = file_rec.get("file", "")
            file_id = self.fetch_file_id(filepath)
            
            total_checks = 0
            defects = []
            
            def add_defect(dtype, sev, elem, trig, exp):
                defect_obj = {
                    "file_id": file_id,
                    "defect_type": dtype,
                    "severity": sev,
                    "element_type": elem,
                    "trigger_text": trig,
                    "expected_text": exp
                }
                defects.append(defect_obj)
                if file_id > 0:
                    try:
                        write_ui_defect(self.cfg, defect_obj)
                    except Exception as e:
                        logger.error(f"Failed to write UI defect to DB: {e}")

            # Check buttons
            for btn in file_rec.get("buttons", []):
                text = btn.get("text", "").strip()
                css = btn.get("class", "").strip()
                if not text:
                    continue
                
                total_checks += 1
                lower_str = text.lower()
                
                # Capitalization Consistency
                expected_cas = self.dominant_casing.get(lower_str, text)
                if text != expected_cas:
                    add_defect("INCONSISTENT_CAPITALIZATION", "LOW", "button", text, expected_cas)
                
                # CSS Consistency
                expected_css = self.dominant_class.get(lower_str, "")
                if css and expected_css and css != expected_css:
                    add_defect("INCONSISTENT_CSS", "MEDIUM", "button", f"{text} ({css})", expected_css)
                
                # Grammar/Spelling/Lorem
                btn_type = btn.get("type", "static")
                if btn_type != "i18n":
                    issues = self.check_spelling_and_lorem(text)
                    for issue in issues:
                        add_defect(issue["type"], issue["severity"], "button", issue["trigger"], issue["expected"])
            
            for header in file_rec.get("headers", []):
                text = header.get("text", "").strip()
                htype = header.get("type", "static")
                if text and htype != "i18n":
                    total_checks += 1
                    issues = self.check_spelling_and_lorem(text)
                    for issue in issues:
                        add_defect(issue["type"], issue["severity"], "header", issue["trigger"], issue["expected"])
            
            for vtext in file_rec.get("visibleTexts", []):
                text = vtext.get("text", "").strip()
                ttype = vtext.get("type", "static")
                if text and ttype != "i18n":
                    total_checks += 1
                    issues = self.check_spelling_and_lorem(text)
                    for issue in issues:
                        add_defect(issue["type"], issue["severity"], "text", issue["trigger"], issue["expected"])

            # Calculate Consistency Score
            passed_checks = max(0, total_checks - len(defects)) 
            score = (passed_checks / total_checks * 100.0) if total_checks > 0 else None
            
            report_data.append({
                "file": filepath,
                "total_ui_elements": total_checks,
                "defects_count": len(defects),
                "consistency_score": score,
                "defects": [{k: v for k,v in d.items() if k != "file_id"} for d in defects]
            })

        return report_data

def main(external_cfg=None):
    logger.info("Initializing UI Consistency and Spell Checker...")
    if external_cfg:
        cfg = external_cfg
    else:
        if not CONFIG_PATH.exists():
            logger.error("Config missing at %s", CONFIG_PATH)
            return
        with open(CONFIG_PATH, "r", encoding="utf-8") as f:
            cfg = yaml.safe_load(f)
        try:
            from dotenv import load_dotenv
            import os
            load_dotenv()
            if "db" not in cfg: cfg["db"] = {}
            cfg["db"]["password"] = os.getenv("MYSQL_PASSWORD", cfg["db"].get("password", ""))
        except ImportError:
            pass

    checker = UIConsistencyChecker(cfg)
    data = checker.load_data()
    if not data:
        logger.warning("No data found or extraction empty.")
        return

    logger.info("Running Pass 1: Global pattern aggregation...")
    checker.pass_one(data)
    
    logger.info("Running Pass 2: Evaluating files...")
    report = checker.pass_two_evaluate_files(data)
    
    with open(OUTPUT_REPORT_PATH, "w", encoding="utf-8") as f:
        json.dump({"uiConsistency": report}, f, indent=2)
        
    logger.info("Task 5 Complete. Generated %s", OUTPUT_REPORT_PATH)

if __name__ == "__main__":
    main()
