base_path: C:/Users/Atharvaso/Desktop/PortalManagement/client/app/src
db:
  database: code_audit_db
  host: localhost
  password: ''
  port: 3306
  user: root
generic_api:
  confidence: MEDIUM
  patterns:
  - axios\.(get|post|put|delete|patch|request)\(
  - (?<!\.)\bfetch\(
  - this\.\$http\.(get|post|put|delete|patch)\(
module: null
mql:
  confidence: HIGH
  pattern: \w+\.\[(\w+)\]
project: digital_university
spelling:
  ignore_words:
  - DU
  - MQL
  - vue
  - Vue
vue_version: 2
