base_path: C:\Users\Atharvaso\Desktop\StudentManagement
db:
  path: audit_history.db
generic_api:
  confidence: MEDIUM
  patterns:
  - axios\.(get|post|put|delete|patch|request)\(
  - (?<!\.)\bfetch\(
  - this\.\$http\.(get|post|put|delete|patch)\(
module: null
mql:
  confidence: HIGH
  pattern: \w+\.\[(\w+)\]
project_name: mkcl_university
spelling:
  ignore_words:
  - DU
  - MQL
  - vue
  - Vue
vue_version: 2
